<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>inc</string>
	</array>
	<key>name</key>
	<string>65c816 Assembly</string>
	<key>patterns</key>
	<array>


		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Status</string>
			<key>match</key>
			<string>(?i)\s*\b(CLC|CLD|CLI|CLV|SEC|SED|SEI)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.65c816.status</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Status</string>
			<key>match</key>
			<string>(?i)\s*\b(REP|SEP)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.65c816.status.repsep</string>
		</dict>

		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Returns</string>
			<key>match</key>
			<string>(?i)\s*\b(RTI|RTS|RTL)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.65c816.return</string>
		</dict>

		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Stack Operations</string>
			<key>match</key>
			<string>(?i)\s*\b(PEA(\.w)?|PEI|PER(\.w)?|PHA|PHB|PHD|PHK|PHP|PHX|PHY|PLA|PLB|PLD|PLP|PLX|PLY)</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.65c816.stack</string>
		</dict>

		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Breakpoint</string>
			<key>match</key>
			<string>(?i)\s*\b(WDM|BRK|COP|STP)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.65c816.breakpoint</string>
		</dict>
		
		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Branches</string>
			<key>match</key>
			<string>(?i)\s*\b(BCC|BCS|BEQ|BIT|BMI|BNE|BPL|BRA|BRL|BVC|BVS)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.65c816.branch</string>
		</dict>

		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Branches</string>
			<key>match</key>
			<string>(?i)\s*\b(JMP|JML|JSR|JSL)(\.b|\.w|\.l)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.65c816.jump</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.65c816.length</string>
				</dict>
			</dict>
		</dict>

		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Branches</string>
			<key>match</key>
			<string>(?i)\s*\b(MVN|MVP)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.65c816.block</string>
		</dict>

	
		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics</string>
			<key>match</key>
			<string>(?i)\s*\b(ADC|AND|ASL|CMP|CPX|CPY|DEC|DEX|DEY|EOR|INC|INX|INY|LDA|LDX|LDY|LSR|NOP|ORA|ROL|ROR|SBC|STA|STX|STY|STZ|TAX|TAY|TCD|TCS|TDC|TSC|TSX|TXA|TXS|TXY|TYA|TYX|TRB|TSB|WAI|XBA|XCE)(\.b|\.w|\.l)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.65c816</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.65c816.length</string>
				</dict>
			</dict>
		</dict>


	</array>
	<key>scopeName</key>
	<string>source.asm.65c816</string>
</dict>
</plist>
