<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>65c816 Assembly</string>
	<key>patterns</key>
	<array>


		<dict>
			<key>comment</key>
			<string>Letters</string>
			<key>match</key>
			<string>(?i)(,?(((\bYA)|(\bA)|(\+?X\b)|(\+Y\b)|(X\+?)|(\bC)|(\bX)|(\bY)|(\bSP)|(\bP))(?=\(|\)|,|\s)))</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.letters</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>GSU Regs</string>
			<key>match</key>
			<string>(?i)\b(\(?R(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15)\)?)\b(?=\(|\)|,|\s)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.gsuregs</string>
				</dict>
			</dict>
		</dict>

		<dict>
			<key>comment</key>
			<string>Stack Operations - Pushes</string>
			<key>match</key>
			<string>(?i)\s*\b(PHA|PHB|PHD|PHK|PHP|PHX|PHY)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.stack.push</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Stack Operations - Pulls</string>
			<key>match</key>
			<string>(?i)\s*\b(PLA|PLB|PLD|PLP|PLX|PLY)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.stack.pull</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Stack Operations - Values</string>
			<key>match</key>
			<string>(?i)\s*\b(PEA|PEI|PER)(\.w)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.stack.value</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.length</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Stack Operations - SPC700</string>
			<key>match</key>
			<string>(?i)\s*\b(POP|PUSH)\b\s+[APXY]\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.stack.spc700</string>
		</dict>




		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Status</string>
			<key>match</key>
			<string>(?i)\s*\b(CLC|SEC)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.status.carry</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Status</string>
			<key>match</key>
			<string>(?i)\s*\b(CLD|SED)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.status.decimal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Status</string>
			<key>match</key>
			<string>(?i)\s*\b(CLI|SEI)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.status.interrupt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Status</string>
			<key>match</key>
			<string>(?i)\s*\b(CLV)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.status.overflow</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>65c816 Mnemonics Status</string>
			<key>match</key>
			<string>(?i)\s*\b(REP|SEP)\b(?=\s+#)</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.status.repsep</string>
		</dict>

		<dict>
			<key>comment</key>
			<string>SPC700 Mnemonics Status</string>
			<key>match</key>
			<string>(?i)\s*\b(SET[CP]|CLR[CPV]|NOTC)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.status.spc700</string>
		</dict>


		
		<dict>
			<key>comment</key>
			<string>Returns</string>
			<key>match</key>
			<string>(?i)\s*\b(RTI|RTS|RTL|RET|RETI)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.return</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Returns - Sleep</string>
			<key>match</key>
			<string>(?i)\s*\b(SLEEP)\b\s+</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.return.sleep</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Returns - Stop</string>
			<key>match</key>
			<string>(?i)\s*\b(STOP)\b\s+</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.return.stop</string>
		</dict>




		<dict>
			<key>comment</key>
			<string>Breakpoints</string>
			<key>match</key>
			<string>(?i)\s*\b(WDM|BRK|COP|STP)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.breakpoint</string>
		</dict>
		



		<dict>
			<key>comment</key>
			<string>Branches</string>
			<key>match</key>
			<string>(?i)\s*\b(BCC|BCS|BEQ|BMI|BNE|BPL|BRA|BRL|BVC|BVS)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.branch</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SPC700's Branches</string>
			<key>match</key>
			<string>(?i)\s*\b(BBC[0-7]*|BBS[0-7]*|CBNE|DBNZ)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.branch.spc700</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>GSU's Branches</string>
			<key>match</key>
			<string>(?i)\s*\b(BLT|BGE)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.branch.gsu</string>
		</dict>




		<dict>
			<key>comment</key>
			<string>Jumps</string>
			<key>match</key>
			<string>(?i)\s*\b(JMP|JML|JSR|JSL)(\.b|\.w|\.l)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.jump</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.length</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>GSU's Jumps</string>
			<key>match</key>
			<string>(?i)\s*\b(LJMP)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.jump.gsu</string>
		</dict>





		<dict>
			<key>comment</key>
			<string>65c816's block move</string>
			<key>match</key>
			<string>(?i)\s*\b(MVN|MVP)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.block</string>
		</dict>




		<dict>
			<key>comment</key>
			<string>Bitwise operations</string>
			<key>match</key>
			<string>(?i)\s*\b(BIT|AND|ORA|EOR|TRB|TSB)(\.b|\.w|\.l)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.bitwise</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.length</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Bitwise operations</string>
			<key>match</key>
			<string>(?i)\s*\b((ASL|LSR|ROL|ROR)(\.b|\.l.|\.w)?)\b</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.bitwise</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.length</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>SPC700's Bitwise operations</string>
			<key>match</key>
			<string>(?i)\s*\b(AND[0-7]*|OR[0-7]*|EOR[0-7]*|NOT[0-7]|CLR[0-7]|SET[0-7]|TCLR|TSET|XCN)(\.b|\.w|\.l)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.bitwise.spc700</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.length</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>GSU's Bitwise operations</string>
			<key>match</key>
			<string>(?i)\s*\b(BIC|XOR|ASR|NOT)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.bitwise.gsu</string>
		</dict>




		<dict>
			<key>comment</key>
			<string>Compare operations</string>
			<key>match</key>
			<string>(?i)\s*\b(CMPW?|CPX|CPY)(\.b|\.w|\.l)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.compare</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.length</string>
				</dict>
			</dict>
		</dict>






		<dict>
			<key>comment</key>
			<string>Math operations</string>
			<key>match</key>
			<string>(?i)\s*\b(ADC|SBC|ADDW|SUBW)(\.b|\.l.|\.w)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.math</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.length</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Math operations</string>
			<key>match</key>
			<string>(?i)\s*\b(((INC|DEC)W?(\.b|\.l.|\.w)?)|(DEX|DEY|INX|INY))\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.math.single</string>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.length</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>SPC700's Math operations</string>
			<key>match</key>
			<string>(?i)\s*\b((DIV)\s+(YA)\s*(,)\s*(X)|(MUL)|(DAA)|(DAS))\b</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.math.spc700</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.letters</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.operator</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.letters</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.math.spc700</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.math.spc700</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.math.spc700</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>GSU's Math operations</string>
			<key>match</key>
			<string>(?i)\s*\b(ADD|SUB|(L|U|F)*MULT|DIV2)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.math.gsu</string>
		</dict>







		<dict>
			<key>comment</key>
			<string>65c816's transfer operations</string>
			<key>match</key>
			<string>(?i)\s*\b(TAX|TAY|TCD|TCS|TDC|TSC|TSX|TXA|TXS|TXY|TYA|TYX)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.transfer</string>
		</dict>




		<dict>
			<key>comment</key>
			<string>No operation</string>
			<key>match</key>
			<string>(?i)\s*\b(NOP)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.nop</string>
		</dict>



		<dict>
			<key>comment</key>
			<string>65c816's wait for interrupt</string>
			<key>match</key>
			<string>(?i)\s*\b(WAI)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.wait</string>
		</dict>



		<dict>
			<key>comment</key>
			<string>Swapping operations</string>
			<key>match</key>
			<string>(?i)\s*\b(XBA|XCE)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.swap</string>
		</dict>


	
		<dict>
			<key>comment</key>
			<string>Load operations</string>
			<key>match</key>
			<string>(?i)\s*\b(LDA|LDX|LDY)((\.b|\.w|\.l)\b)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.accum.load</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.length</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>Store operations</string>
			<key>match</key>
			<string>(?i)\s*\b(STA|STX|STY|STZ)(\.b|\.w|\.l)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.accum.store</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.length</string>
				</dict>
			</dict>
		</dict>




		<dict>
			<key>comment</key>
			<string>SPC700's Move</string>
			<key>match</key>
			<string>(?i)\s*\b(MOV([0-7]|W)?)(\.b|\.w|\.l)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.move.spc700</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.length</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>GSU's Move operations</string>
			<key>match</key>
			<string>(?i)\s*\b(MOVE(B|S|W)*)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.move.gsu</string>
		</dict>




		<dict>
			<key>comment</key>
			<string>SPC700's Interrupts</string>
			<key>match</key>
			<string>(?i)\s*\b(DI|EI)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.interrupts.spc700</string>
		</dict>





		<dict>
			<key>comment</key>
			<string>SPC700's Calls</string>
			<key>match</key>
			<string>(?i)\s*\b(TCALL\s+(0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15))\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.calls.spc700</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.asar.mnemonics.letters</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>SPC700's Calls</string>
			<key>match</key>
			<string>(?i)\s*\b(CALL|PCALL)(\.b|\.w)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.calls.spc700</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SPC700's Calls</string>
			<key>match</key>
			<string>(?i)\s*\b(CALL|PCALL)(\.b|\.w)?\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.calls.spc700</string>
		</dict>




		<dict>
			<key>comment</key>
			<string>GSU's Reg operations</string>
			<key>match</key>
			<string>(?i)\s*\b(FROM|TO|WITH)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.gsu.regops</string>
		</dict>




		<dict>
			<key>comment</key>
			<string>GSU's Loop opcode</string>
			<key>match</key>
			<string>(?i)\s*\b(LOOP)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.gsu.loop</string>
		</dict>

		<dict>
			<key>comment</key>
			<string>GSU's Set Cache</string>
			<key>match</key>
			<string>(?i)\s*\b(CACHE)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.gsu.cache</string>
		</dict>

		<dict>
			<key>comment</key>
			<string>GSU's bank related instructions</string>
			<key>match</key>
			<string>(?i)\s*\b(R(O|A)MB)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.gsu.bank</string>
		</dict>

		<dict>
			<key>comment</key>
			<string>GSU's Set modes</string>
			<key>match</key>
			<string>(?i)\s*\b(ALT[1-3])\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.gsu.alt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>GSU's Plotting instructions</string>
			<key>match</key>
			<string>(?i)\s*\b(PLOT|COLOR|RPIX|CMODE)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.gsu.plot</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>GSU's Regs bytes modifications</string>
			<key>match</key>
			<string>(?i)\s*\b(LOB|HIB|MERGE|SEX|SWAP)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.gsu.alt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>GSU's write to Regs</string>
			<key>match</key>
			<string>(?i)\s*\b(IBT|IWT)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.gsu.regwrite</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>GSU's RAM operations</string>
			<key>match</key>
			<string>(?i)\s*\b(LD(B|W)|LMS*|SMS*|ST(B|W)|SBK|LEA|GET(B(H|L|S)*|C))\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.gsu.ram</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>GSU's Return address</string>
			<key>match</key>
			<string>(?i)\s*\b(LINK)\b</string>
			<key>name</key>
			<string>keyword.asar.mnemonics.return.gsu</string>
		</dict>



	</array>
	<key>scopeName</key>
	<string>source.asm.mnemonics</string>
</dict>
</plist>
